name = "googleforms"
main = "src/worker.js"
compatibility_date = "2024-11-12"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "workers.tablerus.es/googleforms/*"
zone_name = "tablerus.es"

[placement]
mode = "smart"

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true

[[services]]
binding = "ESN_RECRUITMENT"
service = "esn-recruitment"
environment = "production"
entrypoint = "GoogleFormsEntrypoint"

[[services]]
binding = "UTILS"
service = "utils"
environment = "production"
entrypoint = "UtilsWorker"

[[kv_namespaces]]
id = "10a39c9922d447c19bee76aa1e7c0042"
binding = "GOOGLE_FORMS"

[unsafe]
  [[unsafe.bindings]]
  name = "RATE_LIMITER"
  namespace_id = "1"
  type = "ratelimit"

    [unsafe.bindings.simple]
    limit = 10
    period = 10