name = "googleforms"
main = "src/worker.js"
compatibility_date = "2024-11-12"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "workers.tablerus.es/googleforms/*"
zone_name = "tablerus.es"

[placement]
mode = "smart"

[[services]]
binding = "ACTIONS"
service = "actions"
environment = "production"
entrypoint = "ActionsWorker"

[[services]]
binding = "EMAIL_SERVICE"
service = "email"
environment = "production"
entrypoint = "EmailWorker"

[[services]]
binding = "UTILS"
service = "utils"
environment = "production"
entrypoint = "UtilsWorker"

[[kv_namespaces]]
id = "99e606cc58634a1ca7c522fb530cde53"
binding = "ESN_RECRUITMENT"

[[kv_namespaces]]
id = "10a39c9922d447c19bee76aa1e7c0042"
binding = "GOOGLE_FORMS"

[[kv_namespaces]]
id = "7390a7e250aa45ab836178a85b770b91"
binding = "TEMP_KV"

[unsafe]
  [[unsafe.bindings]]
  name = "RATE_LIMITER"
  namespace_id = "1"
  type = "ratelimit"

    [unsafe.bindings.simple]
    limit = 10
    period = 10
